site_name: Pan-Omics Consciousness Engine (PCE)
site_description: A revolutionary computational framework for modeling consciousness emergence from biological complexity
site_author: PCE Development Team
site_url: https://pan-omics-consciousness-engine.readthedocs.io/

repo_name: pan-omic/pce
repo_url: https://github.com/pan-omic/pce
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - meta
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Basic Examples: examples.md
  - Architecture:
    - Overview: architecture/overview.md
    - Core Framework: architecture/core.md
    - MOGIL: architecture/mogil.md
    - Q-LEM: architecture/qlem.md
    - E³DE: architecture/e3de.md
    - HDTS: architecture/hdts.md
    - CIS: architecture/cis.md
  - User Guide:
    - Data Formats: guide/data-formats.md
    - Configuration: guide/configuration.md
    - Advanced Usage: guide/advanced.md
    - Performance Tuning: guide/performance.md
  - Theory:
    - Consciousness Models: theory/consciousness.md
    - Integrated Information Theory: theory/iit.md
    - Global Workspace Theory: theory/gwt.md
    - Quantum Biology: theory/quantum.md
    - Evolutionary Dynamics: theory/evolution.md
  - API Reference:
    - Core: api/core.md
    - Data: api/data.md
    - MOGIL: api/mogil.md
    - Q-LEM: api/qlem.md
    - E³DE: api/e3de.md
    - HDTS: api/hdts.md
    - CIS: api/cis.md
    - Utilities: api/utils.md
  - Patents & IP:
    - Patent Overview: patents/overview.md
    - Novel Algorithms: patents/algorithms.md
    - System Architecture: patents/architecture.md
    - Prior Art Analysis: patents/prior-art.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Release Notes: development/releases.md
    - Roadmap: development/roadmap.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pan-omic/pce
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pce/
  version:
    provider: mike
